spring:
  application:
    name: JOB-SRV
  profiles:
    active: embedded
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#   hibernate batch
    properties:
      "hibernate.jdbc.batch_size": "500"
      "hibernate.jdbc.batch_versioned_data": "true"
      "hibernate.order_updates": "true"
      "hibernate.order_inserts": "true"
    open-in-view: false


server:
  port: 8778

main:
  job:
    port: 10010
    host:
    member-list:
    max-execute-wait-seconds: 10
    max-task-instance: 30
management:
  endpoint:
    health:
      group:
        task:
          showDetails: ALWAYS
          include:
            - 'task'
            - 'diskSpace'

logging.level.org.hibernate.persister.entity: ERROR
