spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: false
  datasource:
    core:
      validation-timeout: 1000
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 10000
      driver-class-name: org.apache.derby.jdbc.AutoloadedDriver
      jdbc-url: 'jdbc:derby:./db/derby/core;create=true'
      pool-name: 'CORE'
      connection-test-query: 'SELECT 1 FROM SYSIBM.SYSDUMMY1'
      transaction-isolation: 'TRANSACTION_REPEATABLE_READ'
    logging:
      validation-timeout: 1000
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 10000
      driver-class-name: org.apache.derby.jdbc.AutoloadedDriver
      jdbc-url: 'jdbc:derby:./db/derby/logging;create=true'
      pool-name: 'LOGGING'
      connection-test-query: 'SELECT 1 FROM SYSIBM.SYSDUMMY1'
      transaction-isolation: 'TRANSACTION_REPEATABLE_READ'


jpa:
  logging:
#    "[hibernate.dialect]": "org.hibernate.dialect.H2Dialect"
    "[hibernate.dialect]": "org.hibernate.dialect.DerbyTenSevenDialect"
  core:
    "[hibernate.dialect]": "org.hibernate.dialect.DerbyTenSevenDialect"


logging:
  level:
    root: info
    org.springframework.boot: info
    akka: debug
