spring:
  application:
    name: JOB-SRV
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#   hibernate batch
#    properties:
#      "hibernate.jdbc.batch_size": "500"
#      "hibernate.jdbc.batch_versioned_data": "true"
#      "hibernate.order_updates": "true"
#      "hibernate.order_inserts": "true"
  datasource:
    core:
      validation-timeout: 1000
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 10000
      driver-class-name: org.apache.derby.jdbc.AutoloadedDriver
      jdbc-url: 'jdbc:derby:./db/derby/core;create=true'
      pool-name: 'LOGGING'
      connection-test-query: 'SELECT 1 FROM SYSIBM.SYSDUMMY1'
      transaction-isolation: 'TRANSACTION_REPEATABLE_READ'
    logging:
      validation-timeout: 1000
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 10000
      driver-class-name: org.apache.derby.jdbc.AutoloadedDriver
      jdbc-url: 'jdbc:derby:./db/derby/logging;create=true'
      pool-name: 'LOGGING'
      connection-test-query: 'SELECT 1 FROM SYSIBM.SYSDUMMY1'
      transaction-isolation: 'TRANSACTION_REPEATABLE_READ'
jpa:
  logging:
    #    "[hibernate.dialect]": "org.hibernate.dialect.H2Dialect"
    "[hibernate.dialect]": "org.hibernate.dialect.DerbyTenSevenDialect"
  core:
    "[hibernate.dialect]": "org.hibernate.dialect.DerbyTenSevenDialect"


server:
  port: 8999
  servlet:
    context-path: /job

main:
  job:
    port: 10010
    host:
    member-list:
    max-execute-wait-seconds: 10
    max-task-instance: 30
management:
  endpoint:
    health:
      group:
        task:
          showDetails: ALWAYS
          include:
            - 'task'
            - 'diskSpace'

logging.level.org.hibernate.persister.entity: ERROR
alarm:
  email:
    enable: false
    host:
    password:
    port:
    protocol: smtp
    username:
    send-to:
