spring:
  application:
    name: JOB-SRV
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#   hibernate batch
#    properties:
#      "hibernate.jdbc.batch_size": "500"
#      "hibernate.jdbc.batch_versioned_data": "true"
#      "hibernate.order_updates": "true"
#      "hibernate.order_inserts": "true"
  datasource:
    core:
      validation-timeout: 1000
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 10000
      driver-class-name: org.h2.Driver
      jdbc-url: 'jdbc:h2:./db/h2/core'
      pool-name: 'CORE-DB'
      connection-test-query: 'SELECT 1'
      transaction-isolation: 'TRANSACTION_REPEATABLE_READ'
    logging:
      jdbc-url: 'jdbc:derby:./db/derby/logging;create=true'
      validation-timeout: 1000
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 10000
      driver-class-name: org.apache.derby.jdbc.AutoloadedDriver
      pool-name: 'LOGGING-DB'
      connection-test-query: 'SELECT 1 FROM SYSIBM.SYSDUMMY1'
      transaction-isolation: 'TRANSACTION_REPEATABLE_READ'
jpa:
  core:
    "[hibernate.dialect]": "org.hibernate.dialect.H2Dialect"
  logging:
    "[hibernate.dialect]": "org.hibernate.dialect.DerbyTenSevenDialect"


server:
  port: 8999

main:
  job:
    port: 10010
    host:
management:
  endpoint:
    health:
      group:
        task:
          showDetails: ALWAYS
          include:
            - 'task'
            - 'diskSpace'

